Description: Pattern with packages for shinano configurations
Name: jolla-configuration-shinano
Requires:
 - patterns-sailfish-applications
 - patterns-sailfish-ui

# Early stages of porting benefit from these:
 - pattern:sailfish-porter-tools

# Jolla Store Items
 - patterns-sailfish-consumer-generic


 - sailfish-content-graphics-z@ICON_RES@
 - jolla-settings-accounts-extensions-3rd-party-all

# For Mozilla location services (online)
 - geoclue-provider-mlsdb

 # Sailfish OS CSD tool for hardware testing
 - csd
Summary: Jolla Configuration shinano
